"""empty message

Revision ID: 0acdf1192ba6
Revises: 38283776a547
Create Date: 2022-02-28 17:14:08.924629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acdf1192ba6'
down_revision = '38283776a547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
