"""empty message

Revision ID: 38283776a547
Revises: 0feb465a1a84
Create Date: 2022-02-28 17:09:59.478894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38283776a547'
down_revision = '0feb465a1a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('customer', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('customer', 'last_name')
    op.drop_column('customer', 'first_name')
    # ### end Alembic commands ###
