"""empty message

Revision ID: 9caba2f6ff77
Revises: fa9973fcaf8a
Create Date: 2022-02-27 23:15:08.703466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caba2f6ff77'
down_revision = 'fa9973fcaf8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('opt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'opt')
    # ### end Alembic commands ###
